# Generated by Django 5.2.12 on 2026-03-11 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('logo_url', models.URLField(blank=True)),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated brand keywords')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_type', models.CharField(choices=[('text', 'Text / Email'), ('url', 'URL'), ('image', 'Image / Logo')], max_length=10)),
                ('input_content', models.TextField()),
                ('target_brand', models.CharField(blank=True, max_length=255)),
                ('gemini_score', models.FloatField(blank=True, null=True)),
                ('hf_score', models.FloatField(blank=True, null=True)),
                ('ensemble_score', models.FloatField(blank=True, null=True)),
                ('verdict', models.CharField(choices=[('safe', 'Safe'), ('suspicious', 'Suspicious'), ('impersonation', 'Impersonation Detected')], max_length=20)),
                ('confidence', models.FloatField()),
                ('explanation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('recommendation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('detection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='api.detectionresult')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
